// <auto-generated />
namespace StockManagement.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Party_IsDeleted_Introduce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Party_IsDeleted_Introduce));
        
        string IMigrationMetadata.Id
        {
            get { return "201806251414524_Party_IsDeleted_Introduce"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
